/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class index_CBlockInputStream */

#ifndef _Included_index_CBlockInputStream
#define _Included_index_CBlockInputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     index_CBlockInputStream
 * Method:    initNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_index_CBlockInputStream_initNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     index_CBlockInputStream
 * Method:    seekNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_index_CBlockInputStream_seekNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     index_CBlockInputStream
 * Method:    readLineNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_index_CBlockInputStream_readLineNative
  (JNIEnv *, jobject);

/*
 * Class:     index_CBlockInputStream
 * Method:    closeFileNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_index_CBlockInputStream_closeFileNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
